/*
===============================================================================
Pareto Analysis (80/20 Rule)
===============================================================================
Purpose:
    - To identify customers contributing the majority of revenue
    - To analyze revenue concentration across the customer base
    - To validate the 80/20 principle (small % of customers generate most revenue)

Business Concept:
    - Pareto Principle states that ~80% of revenue often comes from ~20% of customers
    - This analysis helps prioritize high-impact customers for retention and growth

Use Cases:
    - Sales prioritization
    - Customer value management
    - Revenue concentration analysis
===============================================================================
*/

-- Step 1: Calculate total revenue per customer
WITH customer_revenue AS (
    SELECT
        customer_key,

        -- Total revenue generated by each customer
        SUM(sales_amount) AS customer_revenue
    FROM gold.fact_sales
    GROUP BY customer_key
),

-- Step 2: Rank customers by revenue contribution
-- and calculate cumulative revenue
ranked_customers AS (
    SELECT
        customer_key,
        customer_revenue,

        -- Total revenue across all customers
        SUM(customer_revenue) OVER () AS total_revenue,

        -- Cumulative revenue ordered from highest to lowest contributor
        SUM(customer_revenue) OVER (
            ORDER BY customer_revenue DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS cumulative_revenue
    FROM customer_revenue
)

-- Step 3: Final output – Pareto metrics per customer
SELECT
    customer_key,
    customer_revenue,

    -- Percentage of total revenue contributed by the customer cumulatively
    ROUND(
        cumulative_revenue * 100.0 / total_revenue,
        2
    ) AS cumulative_revenue_pct,

    -- Pareto classification based on cumulative contribution
    CASE
        WHEN cumulative_revenue * 100.0 / total_revenue <= 80
            THEN 'Top Revenue Contributors (≈20%)'
        ELSE 'Remaining Customers (≈80%)'
    END AS pareto_segment

FROM ranked_customers
ORDER BY customer_revenue DESC;
