/*
===============================================================================
RFM Analysis (Recency, Frequency, Monetary)
===============================================================================
Purpose:
    - To segment customers based on their purchasing behavior
    - To identify high-value, loyal, at-risk, and inactive customers
    - To support marketing, retention, and customer value analysis

RFM Dimensions:
    - Recency   : How recently a customer made a purchase
    - Frequency : How often a customer makes purchases
    - Monetary  : How much revenue a customer generates

Business Value:
    - Helps prioritize customers for retention and marketing strategies
    - Identifies top customers contributing most to revenue
===============================================================================
*/

-- Step 1: Build the base RFM metrics per customer
WITH rfm_base AS (
    SELECT
        customer_key,

        -- Recency: number of days since the customer's last purchase
        DATEDIFF(
            DAY,
            MAX(order_date),
            (SELECT MAX(order_date) FROM gold.fact_sales)
        ) AS recency_days,

        -- Frequency: total number of orders placed by the customer
        COUNT(order_number) AS frequency,

        -- Monetary: total revenue generated by the customer
        SUM(sales_amount) AS monetary_value

    FROM gold.fact_sales
    WHERE order_date IS NOT NULL
    GROUP BY customer_key
),

-- Step 2: Assign customer segments based on RFM business rules
rfm_segments AS (
    SELECT
        customer_key,
        recency_days,
        frequency,
        monetary_value,

        -- RFM-based customer classification
        CASE
            WHEN recency_days <= 30 
                 AND frequency >= 10 
                 AND monetary_value >= 5000
                THEN 'Champion'

            WHEN recency_days <= 90 
                 AND frequency >= 5
                THEN 'Loyal'

            WHEN recency_days > 180
                THEN 'At Risk'

            ELSE 'Others'
        END AS rfm_segment

    FROM rfm_base
)

-- Step 3: Final output – customer-level RFM segmentation
SELECT
    customer_key,
    recency_days,
    frequency,
    monetary_value,
    rfm_segment
FROM rfm_segments
ORDER BY monetary_value DESC;
